version: '3.8'

services:

  # Redis Service   
  redis:
    image: "redis" # Use a public Redis image to build the redis service    
    command: ["redis-server", "--bind", "redis", "--port", "6379"]

  # App Service
  app:
    # Configuration for building the docker image for the service
    build:
      context: . # Use an image built from the specified dockerfile in the current directory.
      dockerfile: Dockerfile
    ports:
      - "8080:8080" # Forward the exposed port 8080 on the container to port 8080 on the host machine
    restart: unless-stopped
    depends_on: 
      - redis # This service depends on redis. Start that first.
    environment: # Pass environment variables to the service
      REDIS_URL: redis
