version: '3.8'

services: 
  redis:
    image: "redis"    
    command: ["redis-server", "--bind", "redis", "--port", "6379"]

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    restart: unless-stopped
    depends_on: 
      - redis 
    environment: 
      REDIS_URL: redis:6379
